### PR TITLE
CFP Updates

### PR DESCRIPTION
**Pull request by mkgold**
There are a bunch of changes coming through here, but some of them are the result of my attempt to bring my fork up to date with the CIC master. Really, the only changes I want to add to the CIC master repo are contained in https://github.com/castiron/didh/commit/576703a6a3775c5afef7bf55fffb15ed3d414ec2

The rest can be ignored. Hoping you can cherrypick the ones that matter. Thanks!

### CODE REVIEW

**Comment by zdavis** [comment]
Good timing. I'm working on this project today—upgrading rails, upgrading ruby, improving the deployment process, and various other maintenance tasks. I'll merge these changes in, and should be able to get them out the door by end of day.

**Comment by mkgold** [comment]
Awesome -- thanks, Zach. And sorry for the mess of commits.

**Comment by zdavis** [comment]
I'm going to close this pull request. I've merged 576703a into master, and that's it, which is what I think you want. I'll release this later today—need to fix some deployment issues first.

Zach

**Comment by mkgold** [comment]
Yes, thanks, Zach.

**Pull request closed without merging**
